version: "2.3"

services:
  nginx:
    container_name: nginx-hw2
    image: nginx:latest
    working_dir: /nginx
    volumes:
      - ./nginx:/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
  app:
    container_name: app-hw2
    volumes:
      - ./application:/application
    build:
      context: ./hw_2
      dockerfile: ./docker/python/Dockerfile
    ports:
      - "8000:8000"